# Generated by Django 2.2.2 on 2019-11-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchentlogin',
            name='merchentid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='merchentlogin',
            name='merchentname',
            field=models.IntegerField(),
        ),
    ]
