# Generated by Django 2.2.2 on 2019-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191108_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchentlogin',
            name='merchentname',
            field=models.CharField(max_length=30),
        ),
    ]
