# Generated by Django 2.2.2 on 2019-11-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191108_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=30)),
                ('productprice', models.FloatField()),
                ('merchantid', models.IntegerField()),
            ],
        ),
    ]
